### ISSUE TITLE
It didn't show player's name when enter the server

### ISSUE THREAD

**Issue by linzexin022** [Draylar/game-start#2]
Hi draylar, I tested the welcome message in single player game but it didn't show player's name. Does it work only in multiplayer server? I checked the phrase "{}" in English and in Simplified Chinese (which I think they are the same), I also copied from your README.md but still the same. Here's the screenshot:
![2020-07-30_15 29 35](https://user-images.githubusercontent.com/59003232/88893908-a5a2b100-d279-11ea-9767-b1b3a7a37699.png)

If you need more information please tell me, thanks!

**Comment by Draylar** [comment]
Bleh, sorry, the README was wrong. It should be `{player}`, not `{playername}`. I've updated it now, no update needed (just `playername` -> `player`). Thanks for the report!
