### ISSUE TITLE
support for singleplayer

### ISSUE THREAD

**Issue by milkev** [Draylar/game-start#4]
hello! 
is there a chance for this to support single player worlds in the future? it really seems like a great mod, but i cant run a dedicated server for myself everytime i want to play, unfortunately.

**Comment by Draylar** [comment]
Singleplayer has a server (your client connects to a locally hosted server), so everything in this mod should work perfectly fine, even without a dedicated server. Are there any particular mechanics not working in singleplayer?

**Comment by milkev** [comment]
oh, sorry i didnt realize the mod was still on 1.16.1, i was on 1.16.2 >.<
it causes a crash on attempting to load a world
