### ISSUE TITLE
1.17 use?

### ISSUE THREAD

**Issue by Monster-Zer0** [Draylar/game-start#5]
Tried this mod on 1.17

[Paste of crash](https://paste.alloffabric.com/beyanezevu.http)

Hope life is good Draylar

**Comment by Draylar** [comment]
Done - let me know if it works out! Tested & working on a dedicated server. I removed my dependency on CCA, so this won't preserve information from 1.16.5 worlds (not that anyone would need that), but the mod is much smaller now. 

[GitHub](https://github.com/Draylar/game-start/releases/tag/2.1.1-1.17.1)
[CurseForge](https://www.curseforge.com/minecraft/mc-mods/game-start/files/3503807)

**Comment by Monster-Zer0** [comment]
works great. exactly what I needed. Thanks!
